export const fredSeriesConfigs = [
  {
    key: "retailSales",
    label: "Retail Sales YoY",
    group: "growthLabor",
    category: "消费",
    definition: "YoY %",
    sourceLabel: "Census via FRED",
    seriesId: "RSAFS",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "high",
    alertThreshold: 0.8,
  },
  {
    key: "nonfarmPayrolls",
    label: "Nonfarm Payrolls MoM",
    group: "growthLabor",
    category: "就业",
    definition: "Monthly change",
    sourceLabel: "BLS via FRED",
    seriesId: "PAYEMS",
    frequency: "monthly",
    calculation: "diff",
    unit: "K jobs",
    importance: "high",
    alertThreshold: 120,
  },
  {
    key: "unemploymentRate",
    label: "Unemployment Rate",
    group: "growthLabor",
    category: "就业",
    definition: "Level",
    sourceLabel: "BLS via FRED",
    seriesId: "UNRATE",
    frequency: "monthly",
    calculation: "last",
    unit: "%",
    importance: "high",
    alertThreshold: 0.2,
  },
  {
    key: "initialClaims",
    label: "Initial Jobless Claims",
    group: "growthLabor",
    category: "就业",
    definition: "Level",
    sourceLabel: "DOL via FRED",
    seriesId: "ICSA",
    frequency: "weekly",
    calculation: "lastScaled",
    scale: 0.001,
    unit: "K",
    importance: "high",
    alertThreshold: 15,
  },
  {
    key: "joltsOpenings",
    label: "JOLTS Openings",
    group: "growthLabor",
    category: "就业",
    definition: "Level",
    sourceLabel: "BLS via FRED",
    seriesId: "JTSJOL",
    frequency: "monthly",
    calculation: "last",
    unit: "K",
    importance: "medium",
    alertThreshold: 250,
  },
  {
    key: "housingStarts",
    label: "Housing Starts",
    group: "growthLabor",
    category: "地产",
    definition: "SAAR level",
    sourceLabel: "Census via FRED",
    seriesId: "HOUST",
    frequency: "monthly",
    calculation: "last",
    unit: "K",
    importance: "medium",
    alertThreshold: 80,
  },
  {
    key: "existingHomeSales",
    label: "Existing Home Sales",
    group: "growthLabor",
    category: "地产",
    definition: "SAAR level",
    sourceLabel: "NAR via FRED",
    seriesId: "EXHOSLUSM495S",
    frequency: "monthly",
    calculation: "lastScaled",
    scale: 0.000001,
    unit: "M",
    importance: "medium",
    alertThreshold: 0.2,
  },
  {
    key: "ismManufacturing",
    label: "Manufacturing Output YoY",
    group: "growthLabor",
    category: "制造",
    definition: "YoY %",
    sourceLabel: "Federal Reserve via FRED",
    seriesId: "IPMAN",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "high",
    alertThreshold: 1,
  },
  {
    key: "industrialProduction",
    label: "Industrial Production YoY",
    group: "growthLabor",
    category: "实体经济",
    definition: "YoY %",
    sourceLabel: "Federal Reserve via FRED",
    seriesId: "INDPRO",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "medium",
    alertThreshold: 1,
  },
  {
    key: "cpi",
    label: "Headline CPI YoY",
    group: "inflationFed",
    category: "通胀",
    definition: "YoY %",
    sourceLabel: "BLS via FRED",
    seriesId: "CPIAUCNS",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "high",
    alertThreshold: 0.2,
  },
  {
    key: "coreCpi",
    label: "Core CPI YoY",
    group: "inflationFed",
    category: "通胀",
    definition: "YoY %",
    sourceLabel: "BLS via FRED",
    seriesId: "CPILFENS",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "high",
    alertThreshold: 0.2,
  },
  {
    key: "pce",
    label: "Headline PCE YoY",
    group: "inflationFed",
    category: "通胀",
    definition: "YoY %",
    sourceLabel: "BEA via FRED",
    seriesId: "PCEPI",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "high",
    alertThreshold: 0.15,
  },
  {
    key: "corePce",
    label: "Core PCE YoY",
    group: "inflationFed",
    category: "通胀",
    definition: "YoY %",
    sourceLabel: "BEA via FRED",
    seriesId: "PCEPILFE",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "high",
    alertThreshold: 0.15,
  },
  {
    key: "shelterCpi",
    label: "Shelter CPI YoY",
    group: "inflationFed",
    category: "住房通胀",
    definition: "YoY %",
    sourceLabel: "BLS via FRED",
    seriesId: "CUUR0000SAH1",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "medium",
    alertThreshold: 0.15,
  },
  {
    key: "coreServicesExHousing",
    label: "Services Less Rent of Shelter YoY",
    group: "inflationFed",
    category: "服务通胀",
    definition: "YoY %",
    sourceLabel: "BLS via FRED",
    seriesId: "CUUR0000SASL2RS",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "high",
    alertThreshold: 0.15,
  },
  {
    key: "wageGrowth",
    label: "Average Hourly Earnings YoY",
    group: "inflationFed",
    category: "工资",
    definition: "YoY %",
    sourceLabel: "BLS via FRED",
    seriesId: "CES0500000003",
    frequency: "monthly",
    calculation: "yoyPct",
    unit: "%",
    importance: "high",
    alertThreshold: 0.2,
  },
  {
    key: "effectiveFedFunds",
    label: "Effective Fed Funds",
    group: "inflationFed",
    category: "政策利率",
    definition: "Level",
    sourceLabel: "New York Fed via FRED",
    seriesId: "DFF",
    frequency: "daily",
    calculation: "last",
    unit: "%",
    importance: "medium",
    alertThreshold: 0.1,
  },
  {
    key: "dxyBroad",
    label: "Broad Dollar Index",
    group: "ratesFinancial",
    category: "美元",
    definition: "Level",
    sourceLabel: "Fed H.10 via FRED",
    seriesId: "DTWEXBGS",
    frequency: "daily",
    calculation: "last",
    unit: "",
    importance: "medium",
    alertThreshold: 1.5,
  },
  {
    key: "creditSpread",
    label: "US Corporate OAS",
    group: "ratesFinancial",
    category: "信用",
    definition: "Level",
    sourceLabel: "ICE BofA via FRED",
    seriesId: "BAMLC0A0CM",
    frequency: "daily",
    calculation: "last",
    unit: "%",
    importance: "high",
    alertThreshold: 0.2,
  },
  {
    key: "sp500",
    label: "S&P 500",
    group: "ratesFinancial",
    category: "风险偏好",
    definition: "Level",
    sourceLabel: "S&P DJI via FRED",
    seriesId: "SP500",
    frequency: "daily",
    calculation: "last",
    unit: "",
    importance: "medium",
    alertThreshold: 60,
  },
];

export const treasuryMetricConfigs = [
  {
    key: "treasury2y",
    label: "2Y Treasury",
    group: "ratesFinancial",
    category: "利率",
    definition: "Level",
    sourceLabel: "U.S. Treasury",
    unit: "%",
    importance: "high",
    alertThreshold: 0.12,
  },
  {
    key: "treasury10y",
    label: "10Y Treasury",
    group: "ratesFinancial",
    category: "利率",
    definition: "Level",
    sourceLabel: "U.S. Treasury",
    unit: "%",
    importance: "high",
    alertThreshold: 0.12,
  },
  {
    key: "treasury30y",
    label: "30Y Treasury",
    group: "ratesFinancial",
    category: "利率",
    definition: "Level",
    sourceLabel: "U.S. Treasury",
    unit: "%",
    importance: "medium",
    alertThreshold: 0.12,
  },
  {
    key: "curve2s10s",
    label: "2s10s Curve",
    group: "ratesFinancial",
    category: "曲线",
    definition: "Derived spread",
    sourceLabel: "Derived from U.S. Treasury",
    unit: "bp",
    importance: "high",
    alertThreshold: 10,
  },
  {
    key: "real10y",
    label: "10Y Real Yield",
    group: "ratesFinancial",
    category: "实际利率",
    definition: "Level",
    sourceLabel: "U.S. Treasury",
    unit: "%",
    importance: "high",
    alertThreshold: 0.1,
  },
  {
    key: "breakeven10y",
    label: "10Y Breakeven",
    group: "ratesFinancial",
    category: "通胀预期",
    definition: "Derived spread",
    sourceLabel: "Derived from U.S. Treasury",
    unit: "%",
    importance: "medium",
    alertThreshold: 0.1,
  },
];

export const groupMeta = {
  growthLabor: {
    title: "增长与劳动力",
    lead: "先看最新观测值与对应观测期，再判断增长是在降温、企稳，还是重新走强。",
    perspective: "House View 只负责解释边际变化对盈利、风格和风险偏好的含义，不和原始数据混在一起。",
  },
  inflationFed: {
    title: "通胀与 Fed",
    lead: "把 headline、core、工资和服务通胀放在一起看，核心是判断通胀黏性和政策约束有没有变化。",
    perspective: "House View 聚焦 higher-for-longer 风险、降息空间，以及对久期资产和成长风格的影响。",
  },
  ratesFinancial: {
    title: "利率与金融条件",
    lead: "名义利率、真实利率、曲线、信用和美元共同决定折现率与风险偏好。",
    perspective: "House View 用来表达这些变化更利多成长、价值，还是更偏向防御和现金流资产。",
  },
};
